### PR TITLE
Make fxdata build work on case-sensitive systems

### PR DESCRIPTION
**Pull request by woutersj**
Building the FX data didn't work on my OS (Linux) because of case sensitivity of filenames and commands. This PR should fix this.

### CODE REVIEW

**Review by filmote — CHANGES_REQUESTED** [review]
Hi, I am happy to fix these but are puzzled as to why my Mac (which is of course a linux variant under the covers) didn't complain.  However, I am going to reject the change that to the build path as that is specific to my machine.  Realistically, there is no need for others to build fxdata again if they are simply porting the game to a different homemade Arduboy.

**Comment by woutersj** [comment]
Apparently Apple's filesystem APFS is [case insensitive by default](https://apple.stackexchange.com/questions/415613/what-is-the-default-partition-type-case-sensitive-or-insensitive-in-macbook-pr). Wouldn't have expected that either.

**Comment by filmote** [comment]
Man .. I have been wasting my time typing in commands etc with case sensitive file names and so forth.  Never really noticed that it was ignoring me.

**Comment by filmote** [comment]
Thanks for that contribution.

**Pull request merged**
